### ISSUE TITLE
Fix the search bar styling on the donor.php and donee.php pages.

### ISSUE THREAD

**Issue by rustyriedel** [rustyriedel/donationDatabase#4]
The search bar spans the entire length of the page, it should match the width of the content div.

**Comment by taylorluna** [comment]
The commit I just pushed fixes its appearance on the page but I cannot confirm that it still functions correctly. It did not work on my end before the commit (and continues to not work after).

**Comment by rustyriedel** [comment]
Tested. It works perfectly.
